name: E2E tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 20
    runs-on: web-tools
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
      options: --shm-size=1gb --ipc=host --cap-add=SYS_ADMIN
    env:
      HOME: /root
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
    steps:
      - uses: actions/checkout@v5

      - run: corepack enable

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: pnpm build

      - name: Run Playwright tests
        run: pnpm run test:e2e --shard=${{ matrix.shard }}
